apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: trace-collector
  namespace: trace-dra-test
  labels:
    app: trace-collector
spec:
  selector:
    matchLabels:
      app: trace-collector
  template:
    metadata:
      labels:
        app: trace-collector
    spec:
      serviceAccountName: trace-dra-driver
      priorityClassName: system-node-critical
      containers:
      - name: alloy
        image: grafana/alloy:latest
        args:
        - run
        - /etc/alloy/config/
        - --server.http.listen-addr=0.0.0.0:12345
        ports:
        - containerPort: 12345
          name: admin-http
        volumeMounts:
        - name: alloy-config
          mountPath: /etc/alloy/config
        - name: alloy-sockets
          mountPath: /var/run/alloy
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      - name: driver
        image: ko://github.com/abhinavdahiya/k8s-dra-driver-trace-collector
        securityContext:
          privileged: true
          runAsUser: 0
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CONFIG_FILE
          value: /etc/trace-dra-driver/config.yaml
        volumeMounts:
        - name: plugins-registry
          mountPath: /var/lib/kubelet/plugins_registry
        - name: plugins
          mountPath: /var/lib/kubelet/plugins
        - name: driver-config
          mountPath: /etc/trace-dra-driver
          readOnly: true
        - name: alloy-config
          mountPath: /etc/alloy/config
        - name: alloy-sockets
          mountPath: /var/run/alloy
        - name: cdi
          mountPath: /var/run/cdi
        - name: alloy-admin-config
          mountPath: /admin-config
          readOnly: true
        - name: checkpoint
          mountPath: /var/lib/trace-dra-driver
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      volumes:
      - name: plugins-registry
        hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: Directory
      - name: plugins
        hostPath:
          path: /var/lib/kubelet/plugins
          type: DirectoryOrCreate
      - name: driver-config
        configMap:
          name: trace-dra-driver-config
      - name: alloy-config
        emptyDir: {}
      - name: alloy-sockets
        hostPath:
          path: /var/run/alloy
          type: DirectoryOrCreate
      - name: cdi
        hostPath:
          path: /var/run/cdi
          type: DirectoryOrCreate
      - name: checkpoint
        hostPath:
          path: /var/lib/trace-dra-driver
          type: DirectoryOrCreate
      - name: alloy-admin-config
        configMap:
          name: alloy-admin-config
          optional: true
