apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: trace.example.com
spec:
  selectors:
  - cel:
      expression: "device.driver == 'trace.example.com'"
  extendedResourceName: trace.example.com/capacity
